"""Add list_price to Item

Revision ID: 7fd15728d8fc
Revises: 3d14ecc1e0e6
Create Date: 2025-10-03 11:17:02.972002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd15728d8fc'
down_revision = '3d14ecc1e0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('list_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
